project:
  type: website
  output-dir: docs

website:
  title: "LIMS Project Docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/user-reference/user-index.html
        text: User Reference
      - href: pages/database/database-index.html
        text: Database
      - href: pages/application/application-index.html
        text: Application

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



