---
title: "General Use Patterns"
format:
    html: default
    pdf:
        documentclass: scrartcl
        papersize: letter
        mainfont: "Arial"
        monofont: "Consolas"
        monofontoptions: 
            - Color=79329E
            - Size=.75em
---

This document explains some general patterns and behavior in the LIMS app that are relevant to most users, regardless of which tab you use.  I'm diving this into three sections: 

- **Data Connection**: patterns related to the data connection, how that affects the application's behavior, and what you need to do about it
- **Components**: a list of individual components or entry fields that are common across tabs, like the `Data Grid` and `Save` button, and how they work
- **State Behavior**: the three "states" `Clear`, `Microbe/Type Selected` and `Existing Batch Selected` and how they affect the way the various components behave

## Data Connection

### Reading Data FROM the Database

If the application is set up correctly and is not in `Test Mode`, then when it launches it will spend a few seconds fetching data from the database.  It does not store data locally between sessions, so it has to fetch *everything* from scratch in this first load.  This is part of why startup is a bit slow.

Once it loads, it holds the data it fetched in the application's temporary memory.  This data takes up space on your computer while the app is running, but will be erased completely when the app closes and can't hold on to it anymore.    

Storing the data locally on your computer means that the applciation doesn't have to spend time fetching it from the database over and over again, so you can filter and sort and view data across all tabs fairly quickly.  It does come with two drawbacks, however: 
- It makes the application take up a lot of space while it's running.  To soften the impact, keep the date range settings limited to only what you actually need, so the app isn't wasting space on old irrelevant data.  [See Settings and Versions for how to change the date range](versions-and-settings.html)
- It means that the data doesn't update automatically when someone else makes changes to the central database.  Your app is basically using a copy that it made when it started up, and it will gradually get more and more out-of-date the longer it runs without a refresh.  To correct for this, you can manually refresh it at any time by clicking the little yellow cricle arrow in the top righthand corner.  This refresh will make the app pause for a moment as it fetches the data, like it did during the initial load.  It refreshes *most* data but not quite all; some things that only rarely change, like microbes and recipes, are left out in order to make the refresh a little faster.  If you think a refresh didn't update everything that you expected, try **closing and reopening the program to ensure that *everything* is up-to-date.**

### Making Edits TO the Database

it is **strongly** recommended that you do a refresh before making changes if you've left LIMS open and idle for more than a few mintues.  You want to make sure that you're editing the actual, current database and not an outdated idea of it.  It's unlikely that your change would ever be in conflict with a change someone else made after your last refresh, but it's not *impossible*.  The SQL database has a fair ability to protect itself from changes that would break its logic, but you might get an error or accidentally duplicate someone else's work.

When you click *Save* or *Delete*, then the application will connect with the database to apply those changes there.  **It will always pop up a window and ask you if you're sure before it changes the database.**  If you click OK, it makes your change and then also performs a limited fetch of just the data that is *affected* by your change, so that you can see your change applied and know that it was successful.  This transaction will also cause the program to pause for a moment.

These limited updates that happen when you make it seem like the app has updated it's data, but be aware that it was not a full refresh.  If someone else made a change in a different section of the database not immediately related to your change, then that won't show up until you do a full manualy refresh by clicking the yellow circle arrow.

## Components
The application is organized into tabs that each manage a different **Stage** of production.  [Read more about Tabs and Stages here](tabs-and-stages.html). The exception to this is the `Search` tab at the beginning of the row; this was meant to be a much more robust feature for complex querying of the data, but remains unfinished.

When you click from one tab to the next, anything you entered into the previous tab is cleared.

### Data Grid

Every tab's basic layout includes a `data grid` on the left side of the layout.

By default they will display in reverse chronological order (newest at the top) but you can change the sort order by clicking on the column headers.  When you first click on a header, is will sort on that column's values in *ascending* order.  Click on that same header again and it will sort on the same column in reversed order.  Every tab has different columns depending on what's most relveant to that stage, but all columns can be sorted on.

All tabs but the `Search` tab display the batches for that particular stage, with columns for important relevant data like batch number, start date, parent batch, and cfus.  To view a more complete set of data about the batch, you can double-click it and the form on the righthand side will populate with the batch details.

### Entry Form

All tabs but `Search` have a form on the right side of the display.  You can use this form both to enter a new batch, or to view or edit data about an existing batch.

The specific data fields will be particular to the tab stage, but there are a few things they all share:

#### Microbe or Type Dropdown
`Mother Stock` through `Ferment` all use only one microbe at a time, whereas `Stabilized` through `Final Product` have more complex recipes.  But for all tabs, selecting an item from this dropdown will filter tge righthand data grid to show only batches of that type, and set up the rest of the form for the potential input of a new batch of that type.

#### Start Date
All stages have `Start Date` as a data field, and you can either enter it here by typing or select the date you want int he pop-out calendar.  If you enter a date before entering a batch number, then the batch number with auto-populate with a 6-digit code based off that date in the order of YYMMDD.  If there is already a batch number entered, then selecting a date will not affect it; the batch and date match by default, but you are allowed to overrride the default.

#### Batch Number
All stages also have a `Batch Number` field.  If you manually type in a 6-digit number here before selecting a date, and the number *works* as a YYMMDD date, then itwill auto-populate the date to match the number you type.  If there is already a date selected, then you can change the batch number without affecting it.  Again, the batch and date match by default, but you are allowed to overrride the default.

#### Initials
Here you can manually type your initials, to mark who did the work of entering this data.  This is a simple text field that does not limit you to a "correct" list of initials; the preferred format is 3 letters, but that's not enforced.

#### Notes
All stages have a `Notes` field.  Inevitably there are edge cases and exceptions that don't quite fit into the default data fields, so notes allows you to record any other important information that doesn't fit the normal schema.  

#### Add New
In the top right of the lefthand form is a small checkbox that says `Add New`.  This is marked by default when you first open a tab, and indicates that anything you enter into the form below will be part of a new bathc if you click `Save`.  

It will *unmark* itself automatically if you double-click something from the righthand data grid, because then you are viewing an existing batch.  If you change or add anything to the form when `Add New` is unchecked and click `Save`, then your changes will be saved to the selected existing batch.

You can *manually* select this checkbox when you are viewing an existing batch in order to deselect it and return to a cleared form.

#### Delete and Clear
All stages have a button at the bottom of the page which appears as `Delete` when you have selected a specific batch, and `Clear` when you have not.

For `Delete`, it will be grayed out if you are in Read Only mode, or if the batch you've selected can't be deleted.  The system prevents you from deleting batches that have certain complex data connections, to avoid damaging the data structure.  The exact rules vary between stages, but in general new and incomplete entries can be deleted, but the older they are the more likely they are to be locked in the deeper data web.

If you're entering a new batch, then the Delete button will be a `Clear` button instead, and simply clear the data you've entered into the form.

#### Save
Some stages have more complex entry forms than others, but all of them use the green `Save` button in the same way.  The Save button is always active if you're not in Read Only mode.  If you haven't completed all necessary parts of the form, then when you click Save a popup will tell you so.  

You can either enter the information for a new batch, or select an existing batch fromt he fighthand data grid and make edits or additon.  When you've entered your information, you must click the `Save` button to actually push that information to the database. 

### Recipe Box
Because of the data structure of the stages, the `Stabilized Liquid` thought `Final Product` tabs use the Recipe Box in theior entry forms.  

The recipe box will be blank when you first enter the tab or if you clear the form, but if you select a type from the dropdown it will populate itself according to the appropriate recipe.  For `DMP` this may be empty, depending on what you select.

The qty values for the infredients will auto-populate with the correct volumes for the given total qty of the batch.  *While the batch is still new*, you can edit the total qty to re-caclulate the ingredient amounts as well.  You are allowed to override these values.  Once you save your new batch to the database, if you select and view it again, then the form will stop automatically updating the qtys.  This is to avoid accidentally editing an overriden value.

There will be one box for each ingredient in the recipe, with an entry field line. Within each ingredient box you can also click the green plus button to add another line for that ingredient, if you used multiple batches.  You can delete extra lines by clicking onthe red minus button ,but only when you have more than one.  You can't delete the last single line, because each ingredient must have at least one item.

For some stages, you will see batches with a number `000000`.  These 0-batches are meant to be used as a last resort if you don't have the correct data to fill in that part of the form.  Using them creates a sort of cauterized break in the data chain, so only use them if you have no other choice.

If it's a microbial ingredient, then you will be given a dropdown of exisiting potential batches.  The app's logic tries to keep these dropdowns up-to-date by only showing batches with a `qty` of more than 0.  If you think something should be showing up in a dropdown and it's missing, check the batch in its own tab.  It's qty may be the issue, and you can manually adjust it there to make it appear in the dropdown elsewhere.

If it's a non-microbial incredient then you can manually type the batch number yourself into a text field.  You have to type something for this field, but the application has no error-checking mechanism.  You can type "N/A" here if there is no batch number.


## State Behavior

For all stages tabs, there are three main `states` that the tab can be in.

- Clear
- Microbe/Type Selected
- Existing Batch Selected

These states affect how various elements in the tab appear and behave, and will each be addressed indivudually.

### Clear State

#### How to Tell
In this state, no microbe or type has been selected, and so the data grid on the right side of the display will show *all** batches, not be filtered to a specufruc type.  The `Add New` checkbox will be checked and graye dout so you can't change it.

#### How to Get There
When you first open a tab, it's state is clear by default.  If you're in a `Microbe/Type Selected` state, you can lcik the red `Clear` button at the bottom of the display.  If you're in a `Existing Batch Selected` state, you can click the `Add New` checkbox at the top of the form.

#### Effect on the Data Grid
In a `Clear` state you should see all batches listed in the righthand grid with no filtering.

#### Effect on the Form
In a `Clear` state the form has not adjusted to accomodate a particular microbe or type of batch.  You can enter some data, things like `Dtart Date` or `Initials` or `Notes` that are not specific to a batch type, but parent batch dropdopwns and recipe boxes will be empty.

#### Effect on the Delete/Clear Button
In a `Clear` state you should have a red `Clear` button at the bottom of the form.

#### Effect on the Save Button
In a `Clear` state you can click the `Save` button (unless you're in Read Only mode) but it will trigger a dialog box telling you that you haven't filled in all necessary fields.

### Microbe/Type Selected

#### How to Tell
In this state the righthand datagrid will be filtered to show only batches for the selected microbe or type in the dropdown at the top of the form, but the `Add New` checkbox will still be checked and disabled.

#### How to Get There
From a `Clear` state you can select a microbe or type from the dropdown at the top of the form to switch to a `Microbe/Type Selected` state oriented around the selected item.

If you're in a, `Existing Batch Selected` state you need to first click `Add New` to revert to a `Clear` state, and then select something fromt he dropdown.

#### Effect on the Data Grid
In a `Microbe/Type Selected` state the data grid is fitlered to show only batches for the selected type.

#### Effect on the Form
In a `Microbe/Type Selected` state the form may still be mostly empty, but has been readjusted to fit the selected type.  If the stage has a recipe, then the recipe box will display it, and any parent or microbial ingredients dropdowns will be populated with appropriate options.  Default qtys will be applied, and if ther is a reciple then those qtys will be auto-calculated whenever you change the total qty, though you can override them.

#### Effect on the Delete/Clear Button
In a `Microbe/Type Selected` state you should still have a red `Clear` button at the bottom of the form.  Clicking it will clear the form and return you to a `Clear` state.

#### Effect on the Save Button
In a `Microbe/Type Selected` state you can click the `Save` button (unless you're in Read Only mode) and if you have all the required fields filled it will save your entry as a new batch.

### Existing Batch Selected

#### How to Tell
In this state the righthand datagrid will be filtered to show only batches for the selected microbe or type in the dropdown at the top of the form, *and* the `Add New` checkbox will by unchecked and active.  The form will be populated with the existing data, and some fields like the batch number will be grayed out so you can't change them.

#### How to Get There
From any state, you can double-click on an item in the righthand data grid to select it and set the tab state around it.

#### Effect on the Data Grid
In a `Existing Batch Selected` state the data grid is filtered to show only batches for the selected type.  Some tabs add additional filtering to show only other batches with the same parent.

#### Effect on the Form
In a `Existing Batch Selected` state the form will be readjusted to fit the selected batch's type, and then populated with exisiting data from the database.  Some fields will be grayed out so you can't change them. Qtys will no longer auto-calculate, to avoid accidentally resetting an intentionally overridden value.

#### Effect on the Delete/Clear Button
In a `Existing Batch Selected` state you should now have a `Delete` button at the bottom of the form inseatd of `Clear`.  It may be grayed out and inactive if the batch cannot be deleted due to relationships with other data in the database.  If it's red then it's active and clicking it will delete the selected batch from the database.  

#### Effect on the Save Button
In a `Existing Batch Selected` state you can click the `Save` button (unless you're in Read Only mode) and whatever changes you've made will replace the previous data about the selected batch in the database.

## Summary Table of Components and States

| Component | Clear State | Microbe/Type Selected State | Existing Batch Selected State |
|:----------|:------------|:----------------------------|:------------------------------|
| Data Grid | all/unfiltered | filtered by microbe/type | filtered by type or parent batch |
| Entry Form | empty, generic | empty, strucutred for type | populated with existing data, structured for type |
| Add New Checkbox | checked, disabled | checked, disabled | unchecked, enabled, clicking stes state to `Clear` |
| Microbe/Type Dropdown | blank, enabled | selected, enabled | selected, disabled |
| Batch Number | blank, enabled | blank, enabled | filled, disabled |
| Parent Batch | blank, no options | blank, options available | selected, diabled |
| Recipe Box | blank, no options | blank, recipe options available | blank or filled, recipe options available |
| Save Button | active, dialog tells you not enough data | active, saves new if all required fields filled | active, saves over existing batch |
| Clear/Delete Button | Clear, clears form | Clear, clears form, returns state to `Clear` | Delete, may be disabled, deletes selected batch |

<!-- ...

Each tab has particular functions, but some things are general:

tab patterns:
    data table of past stuff on the right, form on the left
    can sort table by any of the columns
    can double click to select an item and view it in the form on the left
    can clear out the selected item from the form by clicking "add new" checkbox

    the left has a form for entering new items or viewing/editing details of existing ones. 
    you can also sort the righthand table by selecting microbe/product:
        that both filters the table
        and sets some defaults for the form to enter a new one of those
        filters down ingredients and recipe stuff to what's relevant for that item
    clear out the item-specific filtering by clicking "clear" button at bottom

    microbe/type select filtering
    add new/select batch
    delete/clear -->