---
title: "mother_batches"
format:
    html: default
    pdf:
        documentclass: scrartcl
        papersize: letter
        mainfont: "Arial"
        monofont: "Consolas"
        monofontoptions: 
            - Color=79329E
            - Size=.75em
---

## Purpose

To track all batches of Mother Stock.

## Referenced By

- working_batches

## References

- microbe_types.code

## Primary Key

The batch number is used as the primary key.  Later stages had more organic batch numbering systems that could be coopted by the LIMS system, but in the case of mother and working stocks, different batches were only differentiated by the date they were made.  

To create batch numbers that could work in LIMS, I translated those dates into the YYMMDD format used elsewhere, and added 

## Columns

| column name | data type | constraints | purpose |
|:------------|:----------|:------------|:--------|
| batch | varchar(20) | Primary Key, Not Null | To be the unique identifier for other tables to reference.  It's assumed that mother stocks made on the same day will have have the same batch number. |
| microbe_code | varchar(10) | Foreign Key, Not Null | Which microbe;  references the microbe_types table and connects the microbe-specific data there. |
| qty | integer | - | The number of tubes originally made. |
| qty_remaining | integer | - | The number of tubes still available. |
| start_date | datetime | Not Null | When the mother stock was made or obtained. |